#pragma once

#define RAFTEL_MOUSE_BUTTON_1         0
#define RAFTEL_MOUSE_BUTTON_2         1
#define RAFTEL_MOUSE_BUTTON_3         2
#define RAFTEL_MOUSE_BUTTON_4         3
#define RAFTEL_MOUSE_BUTTON_5         4
#define RAFTEL_MOUSE_BUTTON_6         5
#define RAFTEL_MOUSE_BUTTON_7         6
#define RAFTEL_MOUSE_BUTTON_8         7
#define RAFTEL_MOUSE_BUTTON_LAST      RAFTEL_MOUSE_BUTTON_8
#define RAFTEL_MOUSE_BUTTON_LEFT      RAFTEL_MOUSE_BUTTON_1
#define RAFTEL_MOUSE_BUTTON_RIGHT     RAFTEL_MOUSE_BUTTON_2
#define RAFTEL_MOUSE_BUTTON_MIDDLE    RAFTEL_MOUSE_BUTTON_3